package com.jobPortal.beans;
// Generated Jul 1, 2024 3:52:48 PM by Hibernate Tools 3.2.4.GA



/**
 * AppliedJob generated by hbm2java
 */
public class AppliedJob  implements java.io.Serializable {


     private Long appliedJobId;
     private String status;
     private String isActive;
     private String createdBy;
     private String createdDate;
     private String modifiedBy;
     private String modifiedDate;
     private PostJob postJob;
     private UserRegister userRegister;

    public AppliedJob() {
    }

    public AppliedJob(String status, String isActive, String createdBy, String createdDate, String modifiedBy, String modifiedDate, PostJob postJob, UserRegister userRegister) {
       this.status = status;
       this.isActive = isActive;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.postJob = postJob;
       this.userRegister = userRegister;
    }
   
    public Long getAppliedJobId() {
        return this.appliedJobId;
    }
    
    public void setAppliedJobId(Long appliedJobId) {
        this.appliedJobId = appliedJobId;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public String getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public String getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(String modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public PostJob getPostJob() {
        return this.postJob;
    }
    
    public void setPostJob(PostJob postJob) {
        this.postJob = postJob;
    }
    public UserRegister getUserRegister() {
        return this.userRegister;
    }
    
    public void setUserRegister(UserRegister userRegister) {
        this.userRegister = userRegister;
    }




}


