package com.jobPortal.beans;
// Generated Jul 1, 2024 3:52:48 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Company generated by hbm2java
 */
public class Company  implements java.io.Serializable {


     private Long companyId;
     private String companyName;
     private String companyEmail;
     private String companyPassword;
     private String isActive;
     private String createdBy;
     private String createdDate;
     private String modifiedBy;
     private String modifiedDate;
     private String companyLogo;
     private UserAccount userAccount;
     private Set postJobs = new HashSet(0);
     private Set contactUsers = new HashSet(0);

    public Company() {
    }

    public Company(String companyName, String companyEmail, String companyPassword, String isActive, String createdBy, String createdDate, String modifiedBy, String modifiedDate, String companyLogo, UserAccount userAccount, Set postJobs, Set contactUsers) {
       this.companyName = companyName;
       this.companyEmail = companyEmail;
       this.companyPassword = companyPassword;
       this.isActive = isActive;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.companyLogo = companyLogo;
       this.userAccount = userAccount;
       this.postJobs = postJobs;
       this.contactUsers = contactUsers;
    }
   
    public Long getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public String getCompanyEmail() {
        return this.companyEmail;
    }
    
    public void setCompanyEmail(String companyEmail) {
        this.companyEmail = companyEmail;
    }
    public String getCompanyPassword() {
        return this.companyPassword;
    }
    
    public void setCompanyPassword(String companyPassword) {
        this.companyPassword = companyPassword;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public String getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public String getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(String modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public String getCompanyLogo() {
        return this.companyLogo;
    }
    
    public void setCompanyLogo(String companyLogo) {
        this.companyLogo = companyLogo;
    }
    public UserAccount getUserAccount() {
        return this.userAccount;
    }
    
    public void setUserAccount(UserAccount userAccount) {
        this.userAccount = userAccount;
    }
    public Set getPostJobs() {
        return this.postJobs;
    }
    
    public void setPostJobs(Set postJobs) {
        this.postJobs = postJobs;
    }
    public Set getContactUsers() {
        return this.contactUsers;
    }
    
    public void setContactUsers(Set contactUsers) {
        this.contactUsers = contactUsers;
    }




}


