package com.jobPortal.beans;
// Generated Jul 1, 2024 3:52:48 PM by Hibernate Tools 3.2.4.GA


import java.sql.Timestamp;

/**
 * ContactUser generated by hbm2java
 */
public class ContactUser  implements java.io.Serializable {


     private Long contactId;
     private String status;
     private String isActive;
     private String createdBy;
     private Timestamp createdDate;
     private String modifiedBy;
     private Timestamp modifiedDate;
     private Company company;
     private UserRegister userRegister;

    public ContactUser() {
    }

    public ContactUser(String status, String isActive, String createdBy, Timestamp createdDate, String modifiedBy, Timestamp modifiedDate, Company company, UserRegister userRegister) {
       this.status = status;
       this.isActive = isActive;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.company = company;
       this.userRegister = userRegister;
    }
   
    public Long getContactId() {
        return this.contactId;
    }
    
    public void setContactId(Long contactId) {
        this.contactId = contactId;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Timestamp getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(Timestamp createdDate) {
        this.createdDate = createdDate;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public Timestamp getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(Timestamp modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public Company getCompany() {
        return this.company;
    }
    
    public void setCompany(Company company) {
        this.company = company;
    }
    public UserRegister getUserRegister() {
        return this.userRegister;
    }
    
    public void setUserRegister(UserRegister userRegister) {
        this.userRegister = userRegister;
    }




}


