package com.jobPortal.beans;
// Generated Jul 1, 2024 3:52:48 PM by Hibernate Tools 3.2.4.GA



/**
 * StateCityData generated by hbm2java
 */
public class StateCityData  implements java.io.Serializable {


     private Long id;
     private String place;
     private Integer locationId;

    public StateCityData() {
    }

    public StateCityData(String place, Integer locationId) {
       this.place = place;
       this.locationId = locationId;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getPlace() {
        return this.place;
    }
    
    public void setPlace(String place) {
        this.place = place;
    }
    public Integer getLocationId() {
        return this.locationId;
    }
    
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }




}


