package com.jobPortal.beans;
// Generated Jul 1, 2024 3:52:48 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;

/**
 * UserRegister generated by hbm2java
 */
public class UserRegister  implements java.io.Serializable {


     private Long userId;
     private String firstName;
     private String lastName;
     private String mobileNo;
     private String emailId;
     private String password;
     private String education;
     private String skills;
     private String state;
     private String city;
     private String isActive;
     private String createdBy;
     private String createdDate;
     private String modifiedBy;
     private String modifiedDate;
     private String resumeFile;
     private UserAccount userAccount;
     private Set appliedJobs = new HashSet(0);
     private Set contactUsers = new HashSet(0);

    public UserRegister() {
    }

    public UserRegister(String firstName, String lastName, String mobileNo, String emailId, String password, String education, String skills, String state, String city, String isActive, String createdBy, String createdDate, String modifiedBy, String modifiedDate, String resumeFile, UserAccount userAccount, Set appliedJobs, Set contactUsers) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.mobileNo = mobileNo;
       this.emailId = emailId;
       this.password = password;
       this.education = education;
       this.skills = skills;
       this.state = state;
       this.city = city;
       this.isActive = isActive;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.resumeFile = resumeFile;
       this.userAccount = userAccount;
       this.appliedJobs = appliedJobs;
       this.contactUsers = contactUsers;
    }
   
    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getMobileNo() {
        return this.mobileNo;
    }
    
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEducation() {
        return this.education;
    }
    
    public void setEducation(String education) {
        this.education = education;
    }
    public String getSkills() {
        return this.skills;
    }
    
    public void setSkills(String skills) {
        this.skills = skills;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public String getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public String getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(String modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public String getResumeFile() {
        return this.resumeFile;
    }
    
    public void setResumeFile(String resumeFile) {
        this.resumeFile = resumeFile;
    }
    public UserAccount getUserAccount() {
        return this.userAccount;
    }
    
    public void setUserAccount(UserAccount userAccount) {
        this.userAccount = userAccount;
    }
    public Set getAppliedJobs() {
        return this.appliedJobs;
    }
    
    public void setAppliedJobs(Set appliedJobs) {
        this.appliedJobs = appliedJobs;
    }
    public Set getContactUsers() {
        return this.contactUsers;
    }
    
    public void setContactUsers(Set contactUsers) {
        this.contactUsers = contactUsers;
    }




}


