package com.jobPortal.beans;
// Generated Jul 1, 2024 3:52:48 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;

/**
 * UserAccount generated by hbm2java
 */
public class UserAccount  implements java.io.Serializable {


     private Long userAccountId;
     private String emailId;
     private String password;
     private String userType;
     private String isActive;
     private String createdBy;
     private String createdDate;
     private String modifiedBy;
     private String modifiedDate;
     private Set userRegisters = new HashSet(0);
     private Set companies = new HashSet(0);

    public UserAccount() {
    }

    public UserAccount(String emailId, String password, String userType, String isActive, String createdBy, String createdDate, String modifiedBy, String modifiedDate, Set userRegisters, Set companies) {
       this.emailId = emailId;
       this.password = password;
       this.userType = userType;
       this.isActive = isActive;
       this.createdBy = createdBy;
       this.createdDate = createdDate;
       this.modifiedBy = modifiedBy;
       this.modifiedDate = modifiedDate;
       this.userRegisters = userRegisters;
       this.companies = companies;
    }
   
    public Long getUserAccountId() {
        return this.userAccountId;
    }
    
    public void setUserAccountId(Long userAccountId) {
        this.userAccountId = userAccountId;
    }
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public String getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }
    
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }
    public String getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(String modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
    public Set getUserRegisters() {
        return this.userRegisters;
    }
    
    public void setUserRegisters(Set userRegisters) {
        this.userRegisters = userRegisters;
    }
    public Set getCompanies() {
        return this.companies;
    }
    
    public void setCompanies(Set companies) {
        this.companies = companies;
    }




}


